// Dashboard Stats
export const GET_DASHBOARD_STATS_REQUEST = 'GET_DASHBOARD_STATS_REQUEST';
export const GET_DASHBOARD_STATS_SUCCESS = 'GET_DASHBOARD_STATS_SUCCESS';
export const GET_DASHBOARD_STATS_FAILURE = 'GET_DASHBOARD_STATS_FAILURE';

// Recent Orders
export const GET_RECENT_ORDERS_REQUEST = 'GET_RECENT_ORDERS_REQUEST';
export const GET_RECENT_ORDERS_SUCCESS = 'GET_RECENT_ORDERS_SUCCESS';
export const GET_RECENT_ORDERS_FAILURE = 'GET_RECENT_ORDERS_FAILURE';

// Sales Over Time
export const GET_SALES_OVER_TIME_REQUEST = 'GET_SALES_OVER_TIME_REQUEST';
export const GET_SALES_OVER_TIME_SUCCESS = 'GET_SALES_OVER_TIME_SUCCESS';
export const GET_SALES_OVER_TIME_FAILURE = 'GET_SALES_OVER_TIME_FAILURE'; 